#handlers/handlers.yml
---
- name: Apache2 restart
  service: name=apache2 state=restarted
  when: ansible_os_family == "Debian"

- name: Httpd enable
  service: name=httpd enabled=yes state=started

#Данный обработчик необходим для корректного отключения selinux в CentOS
- name: CentOS reboot
  command: /sbin/shutdown -r +1
  async: 0
  poll: 0
  ignore_errors: true

