#tasks/centos.yml
---
#- name: Install the Python MySQLB module
 # yum: pkg=python-mysqldb state=present

- name: Install MariaDB
  yum: name={{item}} state=present
  with_items:
    - mariadb
    - mariadb-server
    - MySQL-python

- name: copy .my.cnf file with root password credentials
  template:
    src: centos.my.cnf.j2
    dest: ~/.my.cnf

- name: Start MariaDB
  service: name=mariadb state=started enabled=true



