#tasks/ubuntu.yml
---
- name: Install php5
  apt: name={{item}} state=present
  with_items:
    - php5 
    - php5-cli
    - php5-mysql
    - libapache2-mod-php5
    - php5-gd
    - php5-ldap
    - php5-odbc
    - php5-xmlrpc
    - php5-snmp
    - curl
    - php5-mcrypt
    - php5-dev

  notify:
    - restart apache
