#tasks/ubuntu.yml
---
- name: Install MySQL
  apt: name={{item}} state=present
  with_items:
    - python-mysqldb
    - mysql-server

- name: Start MySQL
  service: name=mysql state=started enabled=true

- name: Copy .my.cnf file with root password credentials
  template:
    src: ubuntu.my.cnf.j2
    dest: ~/.my.cnf