#tasks/ubuntu.yml
---
- name: Install MySQL
  apt: name={{item}} update_cache=yes state=latest
  with_items:
    - python-mysqldb
    - mysql-server

- name: Start MySQL
  service: name=mysql state=started enabled=true

#Для каждого семейства ОС используется свой шаблон для my.cnf, т.к. сокеты и pid-файлы в MySQL и MariaDB имеют разное название
- name: Copy .my.cnf file with root password credentials
  template:
    src: ubuntu.my.cnf.j2
    dest: /etc/.my.cnf

- name: Configure database
  include: dbconfigure.yml
