#mysql/handlers/handlers.yml
---
- name: MySQL restart
  service: name=mysql state=restarted
  when: ansible_os_family == "Debian"

- name: MariaDB restart
  service: name=mariadb state=restarted
  when: ansible_os_family == "Debian"